#!/bin/bash
set -e
chmod 755 /usr/local/bin/hnm                || true
chmod 755 /usr/local/bin/hnm-launcher       || true
update-desktop-database >/dev/null 2>&1 || true
gtk-update-icon-cache /usr/share/icons/hicolor >/dev/null 2>&1 || true
exit 0
